# Generated by Django 5.1.5 on 2025-02-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('representante', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('usuario', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('porta', models.PositiveIntegerField()),
                ('protocolo', models.CharField(choices=[('SSH', 'SSH'), ('TELNET', 'Telnet'), ('WEB', 'Web')], max_length=10)),
                ('x', models.FloatField(default=20.5)),
                ('y', models.FloatField(default=30.5)),
                ('tipo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.empresa')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='BlocoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco_cidr', models.CharField(max_length=18, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('next_hop', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_blocos', to='appisp.blocoip')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos_ip', to='appisp.empresa')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='appisp.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.fabricante')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.modelo'),
        ),
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='pop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.pop'),
        ),
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('speed', models.CharField(choices=[('100M', '100 Mbps'), ('1G', '1 Gbps'), ('10G', '10 Gbps'), ('25G', '25 Gbps'), ('40G', '40 Gbps'), ('100G', '100 Gbps')], default='1G', max_length=10)),
                ('tipo', models.CharField(choices=[('Eletrico', 'Elétrico'), ('Fibra', 'Fibra'), ('Radio', 'Rádio')], default='Fibra', max_length=10)),
                ('observacao', models.TextField(help_text='Para Formata o texto, use < /br> quebra de linha, < strong><strong>Negrito</strong>< /strong>, sem espaços')),
                ('conexao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conexao_inversa', to='appisp.porta')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portas', to='appisp.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('finalidade', models.TextField(blank=True, null=True)),
                ('next_hop', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='appisp.blocoip')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='appisp.equipamento')),
            ],
            options={
                'unique_together': {('bloco', 'ip', 'equipamento')},
            },
        ),
    ]
