# Generated by Django 5.1.5 on 2025-01-20 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('porta', models.PositiveIntegerField()),
                ('protocolo', models.CharField(choices=[('SSH', 'SSH'), ('TELNET', 'Telnet'), ('WEB', 'Web')], max_length=10)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.fabricante')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.modelo')),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.pop')),
            ],
        ),
    ]
