# Generated by Django 5.1.5 on 2025-08-14 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O endereço MAC deve estar no formato XX:XX:XX:XX:XX:XX', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')], verbose_name='Endereço MAC'),
        ),
    ]
