# Generated by Django 5.1.5 on 2025-02-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocoip',
            name='bloco_cidr',
            field=models.CharField(max_length=18),
        ),
    ]
