# Generated by Django 5.1.5 on 2025-02-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0002_alter_blocoip_bloco_cidr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocoip',
            options={'verbose_name_plural': 'Blocos de IP'},
        ),
    ]
