# Generated by Django 5.1.5 on 2025-01-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0002_fabricante_pop_modelo_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appisp.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pop',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appisp.empresa'),
            preserve_default=False,
        ),
    ]
