# Generated by Django 5.1.5 on 2025-08-25 12:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0002_equipamento_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='lado',
            field=models.CharField(choices=[('Frente', 'Frente'), ('Trás', 'Trás')], default='Frente', max_length=10, verbose_name='Lado'),
        ),
        migrations.AddField(
            model_name='porta',
            name='lado',
            field=models.CharField(choices=[('Frente', 'Frente'), ('Trás', 'Trás')], default='Frente', max_length=10, verbose_name='Lado'),
        ),
        migrations.AddField(
            model_name='porta',
            name='mapeamento_traseiro',
            field=models.OneToOneField(blank=True, help_text='Conecta esta porta frontal a uma porta traseira no mesmo patch panel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapeamento_frontal', to='appisp.porta', verbose_name='Mapeamento Traseiro'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O endereço MAC deve estar no formato XX:XX:XX:XX:XX:XX, de 0 a 9 e A a F', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')], verbose_name='Endereço MAC'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('Switch', 'Switch'), ('Roteador', 'Roteador'), ('Servidor', 'Servidor'), ('VMWARE', 'VMWARE'), ('AccesPoint', 'AccesPoint'), ('Passivo', 'Passivo'), ('Olt', 'Olt'), ('Transporte', 'Transporte'), ('Impressora', 'Impressora'), ('Computador', 'Computador'), ('Telefone', 'Telefone'), ('Patch Panel', 'Patch Panel')], default='Switch', max_length=50),
        ),
    ]
