# Generated by Django 5.1.5 on 2025-01-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0003_equipamento_empresa_pop_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('conexao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conexao_inversa', to='appisp.porta')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portas', to='appisp.equipamento')),
            ],
        ),
    ]
