# Generated by Django 5.1.5 on 2025-02-05 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0003_alter_blocoip_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('us', models.PositiveIntegerField(default=20)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.empresa')),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.pop')),
            ],
        ),
        migrations.CreateModel(
            name='RackEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_inicio', models.PositiveIntegerField()),
                ('us_fim', models.PositiveIntegerField()),
                ('lado', models.CharField(choices=[('Frente', 'Frente'), ('Trás', 'Trás')], default='Frente', max_length=10)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.equipamento')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.rack')),
            ],
            options={
                'unique_together': {('rack', 'us_inicio', 'lado')},
            },
        ),
    ]
