# Generated by Django 5.1.5 on 2025-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0003_interface_lado_porta_lado_porta_mapeamento_traseiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='protocolo',
            field=models.CharField(choices=[('SSH', 'SSH'), ('TELNET', 'Telnet'), ('WEB', 'Web'), ('Winbox', 'Winbox'), ('Remoto', 'Remoto'), ('Anydesk', 'Anydesk')], max_length=10),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('Switch', 'Switch'), ('Roteador', 'Roteador'), ('Servidor', 'Servidor'), ('VMWARE', 'VMWARE'), ('AccesPoint', 'AccesPoint'), ('Passivo', 'Passivo'), ('Olt', 'Olt'), ('Transporte', 'Transporte'), ('Impressora', 'Impressora'), ('Computador', 'Computador'), ('Telefone', 'Telefone'), ('Patch Panel', 'Patch Panel'), ('Maquina Virtual', 'Maquina Virtual')], default='Switch', max_length=50),
        ),
    ]
