# Generated by Django 5.1.5 on 2025-11-25 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0004_alter_equipamento_protocolo_alter_equipamento_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_patrimonio', models.CharField(max_length=100, verbose_name='Código do Patrimônio')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Ativo')),
                ('tipo_ativo', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('MOBILIARIO', 'Mobiliário'), ('VEICULO', 'Veículo'), ('OUTRO', 'Outro')], default='HARDWARE', max_length=20, verbose_name='Tipo do Ativo')),
                ('status', models.CharField(choices=[('EM_USO', 'Em Uso'), ('EM_ESTOQUE', 'Em Estoque'), ('EM_MANUTENCAO', 'Em Manutenção'), ('BAIXADO', 'Baixado')], default='EM_ESTOQUE', max_length=20, verbose_name='Status')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Aquisição (R$)')),
                ('nota_fiscal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nota Fiscal')),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor')),
                ('data_baixa', models.DateField(blank=True, null=True, verbose_name='Data da Baixa')),
                ('motivo_baixa', models.TextField(blank=True, null=True, verbose_name='Motivo da Baixa')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonios', to='appisp.empresa', verbose_name='Empresa')),
                ('equipamento', models.OneToOneField(blank=True, help_text='Vincule este ativo a um equipamento funcional, se aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonio', to='appisp.equipamento', verbose_name='Equipamento Vinculado')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appisp.pop', verbose_name='Localização (POP)')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Patrimônio',
                'verbose_name_plural': 'Patrimônios',
                'ordering': ['-data_aquisicao', 'descricao'],
                'unique_together': {('empresa', 'codigo_patrimonio')},
            },
        ),
    ]
