# Generated by Django 5.1.5 on 2025-02-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0004_rack_rackequipamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porta',
            options={'verbose_name_plural': 'Portas equipamento'},
        ),
        migrations.AlterField(
            model_name='rackequipamento',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='appisp.rack'),
        ),
    ]
