# Generated by Django 5.1.5 on 2025-02-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0005_alter_porta_options_alter_rackequipamento_rack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porta',
            options={'verbose_name_plural': 'Equipamentos porta'},
        ),
    ]
