# Generated by Django 5.1.5 on 2025-01-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0005_equipamento_status_equipamento_tipo_equipamento_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='usuario',
            field=models.CharField(default=22, max_length=255),
            preserve_default=False,
        ),
    ]
