# Generated by Django 5.1.5 on 2025-02-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0006_alter_porta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'verbose_name_plural': 'Equipamentos modelo'},
        ),
    ]
