# Generated by Django 5.1.5 on 2025-01-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0006_equipamento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='porta',
            name='speed',
            field=models.CharField(choices=[('100M', '100 Mbps'), ('1G', '1 Gbps'), ('10G', '10 Gbps'), ('25G', '25 Gbps'), ('40G', '40 Gbps'), ('100G', '100 Gbps')], default='1G', max_length=10),
        ),
        migrations.AddField(
            model_name='porta',
            name='tipo',
            field=models.CharField(choices=[('Eletrico', 'Elétrico'), ('Fibra', 'Fibra'), ('Radio', 'Rádio')], default='Fibra', max_length=10),
        ),
    ]
