# Generated by Django 5.1.5 on 2025-02-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0008_customuser_empresa_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(related_name='empresas', to='appisp.customuser'),
        ),
    ]
