# Generated by Django 5.1.5 on 2025-02-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0009_alter_empresa_usuarios'),
    ]

    operations = [
    ]
