# Generated by Django 5.1.5 on 2025-02-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0010_auto_20250206_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuarios',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
