# Generated by Django 5.1.5 on 2025-02-06 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0011_remove_empresa_usuarios_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
    ]
