# Generated by Django 5.1.5 on 2025-02-06 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0012_empresa_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='porta',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appisp.empresa'),
            preserve_default=False,
        ),
    ]
