# Generated by Django 5.1.5 on 2025-02-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0013_porta_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porta',
            name='empresa',
        ),
    ]
