# Generated by Django 5.1.5 on 2025-02-07 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0014_remove_porta_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('Switch', 'Switch'), ('Roteador', 'Roteador'), ('Servidor', 'Servidor'), ('VMWARE', 'VMWARE'), ('AccesPoint', 'AccesPoint'), ('Passivo', 'Passivo')], default='Switch', max_length=50),
        ),
        migrations.CreateModel(
            name='MaquinaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('discos', models.JSONField(default=list)),
                ('memoria', models.PositiveIntegerField(help_text='Memória em MB')),
                ('num_processadores', models.PositiveIntegerField()),
                ('num_cores', models.PositiveIntegerField()),
                ('redes', models.JSONField(default=list)),
                ('sistema_operacional', models.CharField(max_length=255)),
                ('tipo_acesso', models.CharField(choices=[('SSH', 'SSH'), ('TELNET', 'Telnet'), ('RDP', 'Área de Trabalho'), ('WEB', 'Web')], max_length=10)),
                ('porta', models.PositiveIntegerField()),
                ('usuario', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appisp.empresa')),
                ('equipamento', models.ForeignKey(limit_choices_to={'tipo': 'VMWARE'}, on_delete=django.db.models.deletion.CASCADE, to='appisp.equipamento')),
            ],
        ),
    ]
