# Generated by Django 5.1.5 on 2025-02-07 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0015_alter_equipamento_tipo_maquinavirtual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinavirtual',
            name='discos',
        ),
        migrations.RemoveField(
            model_name='maquinavirtual',
            name='redes',
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=50)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discos', to='appisp.maquinavirtual')),
            ],
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='appisp.maquinavirtual')),
            ],
        ),
    ]
