# Generated by Django 5.1.5 on 2025-02-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0016_remove_maquinavirtual_discos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinavirtual',
            name='equipamento',
            field=models.ForeignKey(limit_choices_to={'tipo': 'VMWARE'}, on_delete=django.db.models.deletion.CASCADE, related_name='maquinas_virtuais', to='appisp.equipamento'),
        ),
    ]
