# Generated by Django 5.1.5 on 2025-02-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0017_alter_maquinavirtual_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='observacao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
