# Generated by Django 5.1.5 on 2025-02-10 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0018_equipamento_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='porta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portas', to='appisp.empresa'),
        ),
    ]
