# Generated by Django 5.1.5 on 2025-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appisp', '0019_porta_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinavirtual',
            name='obs',
            field=models.TextField(default=1, help_text='Para Formata o texto, use < /br> quebra de linha, < strong><strong>Negrito</strong>< /strong>, sem espaços'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='porta',
            name='observacao',
            field=models.TextField(help_text='Para formatar o texto, use <br> para quebra de linha, <strong>Negrito</strong> para negrito.'),
        ),
    ]
