version: '3'

services:

   web-ispdoc:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/app
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
      ports:
        - "9000:9000"
      environment:
        MYSQL_ROOT_PASSWORD: Anas2108@@
        MYSQL_DATABASE: ispdoc_db
        MYSQL_USER: ispdoc_user
        MYSQL_PASSWORD: Anas2108@@
      #entrypoint: ["./entrypoint.sh"]
      depends_on:
        - mariadb-ispdoc
      networks:
        - mariadb_network

   mariadb-ispdoc:
      image: mariadb:latest
      container_name: mariadb-ispdoc
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: Anas2108@@
        MYSQL_DATABASE: ispdoc_db
        MYSQL_USER: ispdoc_user
        MYSQL_PASSWORD: Anas2108@@
      ports:
        - "33006:3306"
      volumes:
        - db_data:/var/lib/mysql
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
      networks:
        - mariadb_network

volumes:
  db_data:

networks:
  mariadb_network:
